version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: game_ranks_db
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: GameRanksDb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
